### ISSUE TITLE
Project Structure Problems? Error on fresh install

### ISSUE THREAD

**Issue by EriKWDev** [johnnovak/nim-nanovg#2]
Hi!

It seems that sometimes when I import nanovg and call some procs, I call the wrapper ones directly rather than the ones in nanovg.nim. I doubt that this is it, but isn't the nanovg.nim file and nanovg folder supposed to be inside a `src ` directory and the nimble file have a `srcDir = "src"`? https://github.com/nim-lang/nimble#project-structure
Maybe this confuses the importer? :/ I doubt it though..

I get silly errors like `Error: undeclared identifier: 'nvgCreateContext'` and I get the incorrect (the wrapper) API for `createImageRGBA` requiring a ptr instead of an openArray[byte] which is defined in nanovg.nim.

Things used to work fine, but I reinstalled for testing purposes and now nothing works.

I have tested on Windows, MacOS and Ubuntu and it is the same behavior everywhere :/ 
`nimble install nanovg@0.3.1` with both nim stable and devel.

**Comment by EriKWDev** [comment]
Oh okay, when I went into the cloned directory and typed "nimble develop", My project works again. It seems like the current release is behind the repository. Maybe a release is in order? :)
The examples work since they have `path = ".."`, but it seems like a fresh install from nimble.directory doesn't work.

**Comment by EriKWDev** [comment]
I added `requires "https://github.com/johnnovak/nim-nanovg#099121232829722752d33e0472a11201195feb55"` to my .nimble file to get the current latest commit for anyone else who needs this..

**Comment by johnnovak** [comment]
> Oh okay, when I went into the cloned directory and typed "nimble develop", My project works again. It seems like the current release is behind the repository. Maybe a release is in order? :)
> The examples work since they have `path = ".."`, but it seems like a fresh install from nimble.directory doesn't work.

Yeah, I just push up fixes and don't always release immediately, then I forget about it... my bad, will fix soon.

**Comment by johnnovak** [comment]
Fixed. Better late than never! 😁
