### ISSUE TITLE
Examples fail to run

### ISSUE THREAD

**Issue by matkuki** [johnnovak/nim-nanovg#3]
Hi,

Specs:
- Windows 10 x64
- Nim `devel`
- installed `nim-nanovg` with `nimble install nanovg`

I tried building a couple of examples:
- `demo.nim` runs and immediately stops without an error
- `example_fbo.nim` throws:
```
Traceback (most recent call last)
...\examples\example_fbo.nim(220) example_fbo
...\examples\example_fbo.nim(144) main
...\examples\example_fbo.nim(22) renderPattern
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```
Can this be fixed?

Thanks

**Comment by matkuki** [comment]
@johnnovak 
Is this library still active?

**Comment by johnnovak** [comment]
Yeah, kinda active, but it's a hobby project, so there might be long stretches of inactivity.

You can downgrade to Nim 1.6.0 and it will work. I'm not quite sure why it fails with this error on 1.6.2... I'll figure it out eventually.

**Comment by matkuki** [comment]
Thanks 👍

**Comment by johnnovak** [comment]
@matkuki FYI, the crash happens because of a Nim compiler regression introduced in 1.6.2, it has nothing to do with the library itself:

https://github.com/nim-lang/Nim/issues/19342#event-5888906195

I expect a patch release will be released soon. In the interim, just use 1.6.0 as suggested before.

**Comment by matkuki** [comment]
Thanks for the info 👍👍

**Comment by johnnovak** [comment]
FYI @matkuki , Nim 1.6.4 has been released and now everything works correctly. I've also updated the library and have added two more examples.
